export const PANEL_GUIDE_STEPS = {
  admin: [
    {
      id: 'admin-menu-dashboard',
      title: 'Entrada al dashboard',
      sectionId: 'dashboard',
      selector: '[data-guide-id="admin-menu-dashboard"]',
      summary: 'El menu lateral te mueve entre todos los modulos del panel administrativo.',
      instruction: 'Haz click en "Dashboard" para volver al resumen ejecutivo cuando necesites una vista general del club.',
      highlights: [
        'Sirve como punto de partida para revisar el estado operativo.',
        'Desde aqui puedes saltar al resto de modulos sin salir del panel.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-dashboard-actions',
      title: 'Acciones rapidas del dashboard',
      sectionId: 'dashboard',
      selector: '[data-guide-id="admin-dashboard-quick-actions"]',
      summary: 'El dashboard administrativo incluye atajos directos para los flujos mas usados.',
      instruction: 'Haz click en cualquiera de estas acciones para ir directo a usuarios, pagos, revision financiera o reportes.',
      highlights: [
        'Reduce pasos para tareas operativas frecuentes.',
        'Te deja entrar rapido a los modulos con mas carga diaria.',
      ],
      placement: 'bottom',
    },
    {
      id: 'admin-menu-reportes',
      title: 'Navegacion a reportes',
      sectionId: 'reportes',
      selector: '[data-guide-id="reports-tab-operacion"]',
      summary: 'El modulo de reportes concentra exportes y trazabilidad.',
      instruction: 'Haz click en "Reportes" cuando necesites generar documentos, exportar informacion o revisar historiales persistidos.',
      highlights: [
        'Centraliza reportes operativos, financieros y de padron.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-report-tabs',
      title: 'Pestañas del centro de reportes',
      sectionId: 'reportes',
      selector: '[data-guide-id="reports-tab-operacion"]',
      summary: 'Cada pestaña del centro de reportes organiza una familia distinta de salidas.',
      instruction: 'Haz click en las pestañas para cambiar entre operacion, finanzas, padron e historial segun el tipo de reporte que necesites.',
      highlights: [
        'Operacion: ejecuciones y exportes rapidos.',
        'Finanzas y padron: analisis y descarga por dominio.',
      ],
      placement: 'bottom',
    },
    {
      id: 'admin-report-exports',
      title: 'Exportes de reportes',
      sectionId: 'reportes',
      selector: '[data-guide-id="reports-financial-exports"]',
      summary: 'Los bloques de exporte agrupan formatos por objetivo.',
      instruction: 'Haz click en los botones de exportacion para descargar PDF, CSV o Excel desde la vista consolidada.',
      highlights: [
        'Permite obtener archivos listos para seguimiento y respaldo.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-financial',
      title: 'Revision financiera',
      sectionId: 'revision-financiera',
      selector: '[data-guide-id="financial-review-filters"]',
      summary: 'La revision financiera sirve para detectar riesgo y priorizar cobros.',
      instruction: 'Haz click en "Revision Financiera" para abrir el analisis de deuda, tendencia e ingresos.',
      highlights: [
        'Es la vista de seguimiento financiero mas detallada del panel.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-financial-filters',
      title: 'Filtros de cartera vencida',
      sectionId: 'revision-financiera',
      selector: '[data-guide-id="financial-review-filters"]',
      summary: 'Aqui filtras estudiantes por busqueda, categoria o nivel de deuda.',
      instruction: 'Haz click en estos filtros para recortar la cartera y enfocarte en los casos mas urgentes.',
      highlights: [
        'Ayuda a pasar de una vista global a una cola concreta de trabajo.',
      ],
      placement: 'bottom',
    },
    {
      id: 'admin-menu-users',
      title: 'Gestion de usuarios',
      sectionId: 'usuarios',
      selector: '[data-guide-id="user-management-header"]',
      summary: 'Desde este acceso entras a estudiantes, entrenadores y administradores.',
      instruction: 'Haz click en "Usuarios" para administrar altas, ediciones, roles y estados de cuenta.',
      highlights: [
        'Es el punto de control de cuentas del sistema.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-user-tabs',
      title: 'Pestañas de usuarios',
      sectionId: 'usuarios',
      selector: '[data-guide-id="user-management-tab-athletes"]',
      summary: 'El panel de usuarios separa cada tipo de cuenta por pestañas.',
      instruction: 'Haz click en las pestañas para alternar entre estudiantes, entrenadores y administradores.',
      highlights: [
        'Cada pestaña muestra acciones y permisos acordes al tipo de usuario.',
      ],
      placement: 'bottom',
    },
    {
      id: 'admin-menu-payments',
      title: 'Gestion de pagos',
      sectionId: 'pagos',
      selector: '[data-guide-id="payments-new-button"]',
      summary: 'Este modulo registra mensualidades y corrige estados de pago.',
      instruction: 'Haz click en "Pagos" para abrir el listado y el formulario de registro o edicion.',
      highlights: [
        'Permite controlar la vigencia de cobertura de cada estudiante.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-payments-new',
      title: 'Registrar un pago',
      sectionId: 'pagos',
      selector: '[data-guide-id="payments-new-button"]',
      summary: 'El formulario principal de pagos se abre desde este boton.',
      instruction: 'Haz click en "Registrar Pago" para crear una nueva mensualidad o corregir una existente.',
      highlights: [
        'Desde el formulario eliges atleta, fechas, monto y estado.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-attendance',
      title: 'Control de asistencias',
      sectionId: 'asistencias',
      selector: '[data-guide-id="attendance-bulk-button"]',
      summary: 'Este modulo cubre toma diaria, historico y exportes.',
      instruction: 'Haz click en "Asistencias" para registrar presencia o revisar reportes del entrenamiento.',
      highlights: [
        'Une control operativo y evidencia exportable.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-attendance-bulk',
      title: 'Toma de asistencia',
      sectionId: 'asistencias',
      selector: '[data-guide-id="attendance-bulk-button"]',
      summary: 'La toma diaria arranca desde el modo de registro masivo.',
      instruction: 'Haz click aqui para pasar al modo donde marcas presentes y ausentes por categoria.',
      highlights: [
        'Es el flujo principal para registrar un entrenamiento.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-schedules',
      title: 'Horarios',
      sectionId: 'horarios',
      selector: '[data-guide-id="schedule-new-button"]',
      summary: 'Horarios te permite mantener la estructura de categorias y sus sesiones.',
      instruction: 'Haz click en "Horarios" para crear, editar o depurar la programacion del club.',
      highlights: [
        'Controla categorias y franjas horarias desde un solo modulo.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-schedule-new',
      title: 'Crear horario nuevo',
      sectionId: 'horarios',
      selector: '[data-guide-id="schedule-new-button"]',
      summary: 'Aqui se abre el formulario para nuevas sesiones de entrenamiento.',
      instruction: 'Haz click en "Nuevo Horario" para registrar una nueva franja horaria.',
      highlights: [
        'Tambien puedes editar horarios existentes desde el listado.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-tests',
      title: 'Tests fisicos',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="physical-tests-new-button"]',
      summary: 'Este modulo concentra evaluaciones fisicas y seguimiento deportivo.',
      instruction: 'Haz click en "Tests Fisicos" para abrir el historial de mediciones y el formulario de registro.',
      highlights: [
        'Sirve para cargar pruebas nuevas y revisar progreso.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-tests-new',
      title: 'Registrar test fisico',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="physical-tests-new-button"]',
      summary: 'El alta de una medicion se hace desde este boton.',
      instruction: 'Haz click en "Agregar test fisico" para abrir el formulario de evaluacion del atleta.',
      highlights: [
        'El modulo tambien deja editar y eliminar registros.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-announcements',
      title: 'Anuncios',
      sectionId: 'anuncios',
      selector: '[data-guide-id="announcements-new-button"]',
      summary: 'Aqui se gestionan comunicados para todos los roles.',
      instruction: 'Haz click en "Anuncios" para crear avisos o mantener activos solo los vigentes.',
      highlights: [
        'Permite segmentar mensajes por audiencia.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-announcement-new',
      title: 'Crear anuncio',
      sectionId: 'anuncios',
      selector: '[data-guide-id="announcements-new-button"]',
      summary: 'El formulario de comunicados se abre desde este punto.',
      instruction: 'Haz click en "Nuevo Anuncio" para redactar, segmentar y publicar un comunicado.',
      highlights: [
        'Tambien podras editar, activar o eliminar anuncios existentes.',
      ],
      placement: 'left',
    },
    {
      id: 'admin-menu-gamification',
      title: 'Gamificacion',
      sectionId: 'gamificacion',
      selector: '[data-guide-id="gamification-admin-header"]',
      summary: 'Este modulo administra cosmeticos, logros y metas del sistema.',
      instruction: 'Haz click en "Gamificacion" para abrir el catalogo de elementos visibles para estudiantes.',
      highlights: [
        'Es el centro de configuracion del progreso cosmetico y competitivo.',
      ],
      placement: 'right',
    },
    {
      id: 'admin-gamification-tabs',
      title: 'Pestañas de gamificacion',
      sectionId: 'gamificacion',
      selector: '[data-guide-id="gamification-tab-cosmetics"]',
      summary: 'Cada pestaña separa un tipo de contenido administrable.',
      instruction: 'Haz click en estas pestañas para cambiar entre cosmeticos, logros y metas.',
      highlights: [
        'Desde cada tab puedes crear y activar contenido del sistema.',
      ],
      placement: 'bottom',
    },
    {
      id: 'admin-menu-settings',
      title: 'Configuracion',
      sectionId: 'configuracion',
      selector: '[data-guide-id="profile-settings-header"]',
      summary: 'La ultima seccion del panel permite mantener tu cuenta administrativa.',
      instruction: 'Haz click en "Configuracion" para editar tus datos personales y seguridad.',
      highlights: [
        'Te deja actualizar tu informacion sin salir del panel.',
      ],
      placement: 'right',
    },
  ],
  trainer: [
    {
      id: 'trainer-menu-dashboard',
      title: 'Dashboard del entrenador',
      sectionId: 'dashboard',
      selector: '[data-guide-id="trainer-dashboard-header"]',
      summary: 'El menu lateral organiza el trabajo diario del entrenador.',
      instruction: 'Haz click en "Dashboard" para volver al resumen de atletas, asistencias, tests y pagos.',
      highlights: ['Es tu pantalla de entrada para trabajo diario.'],
      placement: 'right',
    },
    {
      id: 'trainer-dashboard-actions',
      title: 'Acciones rapidas',
      sectionId: 'dashboard',
      selector: '[data-guide-id="trainer-dashboard-quick-actions"]',
      summary: 'Estos atajos te llevan directo a los flujos mas frecuentes.',
      instruction: 'Haz click en una accion rapida para registrar atleta, tomar asistencia, cargar un test o registrar un pago.',
      highlights: ['Reduce pasos cuando la operacion es repetitiva.'],
      placement: 'bottom',
    },
    {
      id: 'trainer-menu-users',
      title: 'Gestion de atletas',
      sectionId: 'usuarios',
      selector: '[data-guide-id="user-management-header"]',
      summary: 'Aqui administras el padron de estudiantes a cargo.',
      instruction: 'Haz click en "Usuarios" para entrar al registro y mantenimiento de atletas.',
      highlights: ['Se usa para altas, ediciones y consulta del padron.'],
      placement: 'right',
    },
    {
      id: 'trainer-athletes-tab',
      title: 'Listado de estudiantes',
      sectionId: 'usuarios',
      selector: '[data-guide-id="user-management-tab-athletes"]',
      summary: 'Esta pestaña concentra el trabajo del entrenador sobre estudiantes.',
      instruction: 'Haz click en la pestaña de estudiantes para crear, editar o revisar deportistas.',
      highlights: ['El entrenador no necesita salir de este flujo para gestionar su grupo.'],
      placement: 'bottom',
    },
    {
      id: 'trainer-menu-attendance',
      title: 'Asistencias',
      sectionId: 'asistencias',
      selector: '[data-guide-id="attendance-bulk-button"]',
      summary: 'El registro de asistencia se hace desde este modulo.',
      instruction: 'Haz click en "Asistencias" para pasar a la toma diaria o al historico.',
      highlights: ['Es el flujo principal antes o durante cada entrenamiento.'],
      placement: 'right',
    },
    {
      id: 'trainer-attendance-bulk',
      title: 'Tomar asistencia',
      sectionId: 'asistencias',
      selector: '[data-guide-id="attendance-bulk-button"]',
      summary: 'El modo masivo es la forma rapida de registrar el entrenamiento del dia.',
      instruction: 'Haz click aqui para abrir la toma de asistencia por categoria y marcar presentes o ausentes.',
      highlights: ['Tambien puedes exportar reportes del dia desde el mismo modulo.'],
      placement: 'left',
    },
    {
      id: 'trainer-menu-tests',
      title: 'Tests fisicos',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="physical-tests-new-button"]',
      summary: 'Este acceso abre las evaluaciones fisicas de los atletas.',
      instruction: 'Haz click en "Tests Fisicos" para revisar pendientes o cargar nuevas mediciones.',
      highlights: ['Sirve para seguimiento de rendimiento y progreso.'],
      placement: 'right',
    },
    {
      id: 'trainer-tests-new',
      title: 'Agregar test fisico',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="physical-tests-new-button"]',
      summary: 'Desde este boton se abre el formulario de evaluacion.',
      instruction: 'Haz click en "Agregar test fisico" para registrar una nueva medicion a un atleta.',
      highlights: ['Puedes usarlo tanto para primeras pruebas como para controles periodicos.'],
      placement: 'left',
    },
    {
      id: 'trainer-menu-payments',
      title: 'Pagos',
      sectionId: 'pagos',
      selector: '[data-guide-id="payments-new-button"]',
      summary: 'El entrenador puede apoyar el control de mensualidades desde este modulo.',
      instruction: 'Haz click en "Pagos" para registrar cobros o consultar el estado de estudiantes.',
      highlights: ['Comparte el mismo flujo operativo que usa administracion.'],
      placement: 'right',
    },
    {
      id: 'trainer-payments-new',
      title: 'Registrar pago',
      sectionId: 'pagos',
      selector: '[data-guide-id="payments-new-button"]',
      summary: 'El alta de pagos se hace desde este boton principal.',
      instruction: 'Haz click en "Registrar Pago" para abrir el formulario y completar la mensualidad del estudiante.',
      highlights: ['Luego puedes corregir o actualizar estados desde la tabla.'],
      placement: 'left',
    },
    {
      id: 'trainer-menu-announcements',
      title: 'Anuncios',
      sectionId: 'anuncios',
      selector: '[data-guide-id="announcements-new-button"]',
      summary: 'Este modulo se usa para mantener comunicados activos.',
      instruction: 'Haz click en "Anuncios" para crear mensajes o editar avisos existentes.',
      highlights: ['Permite publicar informacion deportiva y operativa.'],
      placement: 'right',
    },
    {
      id: 'trainer-announcement-new',
      title: 'Publicar anuncio',
      sectionId: 'anuncios',
      selector: '[data-guide-id="announcements-new-button"]',
      summary: 'La redaccion de un comunicado inicia desde este boton.',
      instruction: 'Haz click en "Nuevo Anuncio" para abrir el formulario y elegir la audiencia del mensaje.',
      highlights: ['Despues podras activarlo, editarlo o eliminarlo.'],
      placement: 'left',
    },
    {
      id: 'trainer-menu-settings',
      title: 'Configuracion personal',
      sectionId: 'configuracion',
      selector: '[data-guide-id="profile-settings-header"]',
      summary: 'La configuracion del entrenador cierra el recorrido.',
      instruction: 'Haz click en "Configuracion" para editar tu perfil o actualizar seguridad de acceso.',
      highlights: ['Mantiene tu cuenta correcta sin salir del panel.'],
      placement: 'right',
    },
  ],
  student: [
    {
      id: 'student-menu-announcements',
      title: 'Anuncios del club',
      sectionId: 'anuncios',
      selector: '[data-guide-id="student-menu-anuncios"]',
      summary: 'El panel del estudiante inicia en anuncios para priorizar novedades.',
      instruction: 'Haz click en "Anuncios" cuando quieras revisar comunicados, avisos o cambios recientes del club.',
      highlights: ['Es la primera parada para enterarte de novedades importantes.'],
      placement: 'right',
    },
    {
      id: 'student-announcements-card',
      title: 'Lectura de anuncios',
      sectionId: 'anuncios',
      selector: '[data-guide-id="student-announcements-card"]',
      summary: 'Aqui ves los comunicados disponibles para ti.',
      instruction: 'Revisa esta lista y usa los filtros del bloque si quieres encontrar un anuncio especifico.',
      highlights: ['Te ayuda a no perder mensajes del club.'],
      placement: 'bottom',
    },
    {
      id: 'student-menu-progress',
      title: 'Mi progreso',
      sectionId: 'progreso',
      selector: '[data-guide-id="student-menu-progreso"]',
      summary: 'Esta seccion concentra tu gamificacion y avance deportivo.',
      instruction: 'Haz click en "Mi Progreso" para abrir tu ruta de progreso, recompensas y comparativas.',
      highlights: ['Reune XP, logros, metas, identidad y competencia.'],
      placement: 'right',
    },
    {
      id: 'student-progress-tabs',
      title: 'Pestañas del progreso',
      sectionId: 'progreso',
      selector: '[data-guide-id="student-progress-tab-summary"]',
      summary: 'El panel de progreso se divide en varias pestañas para separar cada experiencia.',
      instruction: 'Haz click en estas pestañas para cambiar entre resumen, identidad, metas y competencia.',
      highlights: ['Cada pestaña muestra una parte distinta de tu avance.'],
      placement: 'bottom',
    },
    {
      id: 'student-progress-store',
      title: 'Tienda e identidad',
      sectionId: 'progreso',
      selector: '[data-guide-id="student-progress-identity-tab-store"]',
      summary: 'Dentro de identidad puedes entrar a la tienda y personalizacion.',
      instruction: 'Haz click en la subpestaña "Tienda" para comprar o equipar cosmeticos cuando tengas saldo.',
      highlights: ['La personalizacion visible del perfil sale de esta area.'],
      placement: 'bottom',
    },
    {
      id: 'student-menu-payment',
      title: 'Mensualidad',
      sectionId: 'mensualidad',
      selector: '[data-guide-id="student-menu-mensualidad"]',
      summary: 'Esta vista resume tu cobertura activa y si tienes pagos pendientes.',
      instruction: 'Haz click en "Mensualidad" para revisar estado, monto, periodo y fecha de pago.',
      highlights: ['Te ayuda a verificar si estas al dia o proximo a vencer.'],
      placement: 'right',
    },
    {
      id: 'student-payment-card',
      title: 'Estado de tu mensualidad',
      sectionId: 'mensualidad',
      selector: '[data-guide-id="student-payment-card"]',
      summary: 'Este bloque resume si tu mensualidad esta activa, pendiente o proxima a vencer.',
      instruction: 'Revisa aqui el periodo cubierto, la fecha registrada y el tiempo restante de tu pago actual.',
      highlights: ['La informacion se actualiza automaticamente cuando el club registra un pago.'],
      placement: 'left',
    },
    {
      id: 'student-menu-attendance',
      title: 'Mis asistencias',
      sectionId: 'asistencias',
      selector: '[data-guide-id="student-menu-asistencias"]',
      summary: 'Esta seccion muestra tu constancia mensual en entrenamientos.',
      instruction: 'Haz click en "Asistencias" para revisar presentes, entrenamientos registrados e historial reciente.',
      highlights: ['Sirve para medir continuidad y disciplina.'],
      placement: 'right',
    },
    {
      id: 'student-attendance-history',
      title: 'Historial reciente',
      sectionId: 'asistencias',
      selector: '[data-guide-id="student-attendance-history"]',
      summary: 'Dentro del modulo aparece el historial mas reciente de tus asistencias.',
      instruction: 'Revisa este bloque para confirmar en que fechas quedo registrada tu presencia.',
      highlights: ['Te permite validar rapidamente tus ultimas sesiones.'],
      placement: 'left',
    },
    {
      id: 'student-menu-tests',
      title: 'Tests fisicos',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="student-menu-tests-fisicos"]',
      summary: 'Aqui se visualiza tu rendimiento fisico y recomendaciones.',
      instruction: 'Haz click en "Tests Fisicos" para abrir tu perfil de rendimiento y el historial de evaluaciones.',
      highlights: ['Resume evolucion corporal y deportiva.'],
      placement: 'right',
    },
    {
      id: 'student-tests-history',
      title: 'Historial de rendimiento',
      sectionId: 'tests-fisicos',
      selector: '[data-guide-id="student-physical-history"]',
      summary: 'El historial agrupa las mediciones para comparar progreso.',
      instruction: 'Haz scroll hasta este bloque para revisar tus resultados historicos y usarlos como referencia.',
      highlights: ['Es el mejor punto para ver cambios acumulados.'],
      placement: 'left',
    },
    {
      id: 'student-menu-profile',
      title: 'Mi perfil',
      sectionId: 'perfil',
      selector: '[data-guide-id="student-menu-perfil"]',
      summary: 'La ultima seccion del panel combina identidad visible y configuracion de cuenta.',
      instruction: 'Haz click en "Mi Perfil" para personalizar tu imagen y mantener tus datos actualizados.',
      highlights: ['Une presencia visual y configuracion personal.'],
      placement: 'right',
    },
    {
      id: 'student-profile-photo',
      title: 'Foto y avatar',
      sectionId: 'perfil',
      selector: '[data-guide-id="student-profile-photo-actions"]',
      summary: 'La personalizacion principal del estudiante se controla desde este bloque.',
      instruction: 'Haz click en los botones de esta zona para subir tu foto, elegir avatar y guardar la imagen visible del perfil.',
      highlights: ['Afecta sidebar, perfil y presencia en rankings.'],
      placement: 'left',
    },
  ],
};
