create schema if not exists profiles;

create table if not exists profiles.mobile_device_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('android', 'ios', 'web')),
  device_token text not null unique,
  device_name text null,
  app_version text null,
  notifications_enabled boolean not null default true,
  last_seen_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

do $$
declare
  public_relation_kind "char";
begin
  select c.relkind
  into public_relation_kind
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'mobile_device_registrations';

  if public_relation_kind = 'r' then
    insert into profiles.mobile_device_registrations (
      user_id,
      platform,
      device_token,
      device_name,
      app_version,
      notifications_enabled,
      last_seen_at,
      created_at,
      updated_at
    )
    select
      user_id,
      platform,
      device_token,
      device_name,
      app_version,
      notifications_enabled,
      last_seen_at,
      created_at,
      updated_at
    from public.mobile_device_registrations
    on conflict (device_token) do update
    set
      user_id = excluded.user_id,
      platform = excluded.platform,
      device_name = excluded.device_name,
      app_version = excluded.app_version,
      notifications_enabled = excluded.notifications_enabled,
      last_seen_at = excluded.last_seen_at,
      updated_at = excluded.updated_at;
  end if;

  if public_relation_kind = 'v' then
    execute 'drop view public.mobile_device_registrations';
  elsif public_relation_kind = 'r' then
    execute 'drop table public.mobile_device_registrations cascade';
  end if;
end;
$$;

create or replace view public.mobile_device_registrations as
select * from profiles.mobile_device_registrations;

create index if not exists idx_mobile_device_registrations_user_id
  on profiles.mobile_device_registrations(user_id);

create index if not exists idx_mobile_device_registrations_enabled
  on profiles.mobile_device_registrations(notifications_enabled);

alter table profiles.mobile_device_registrations enable row level security;

drop policy if exists "mobile_device_registrations_select_own" on profiles.mobile_device_registrations;
create policy "mobile_device_registrations_select_own"
on profiles.mobile_device_registrations
for select
using (auth.uid() = user_id);

drop policy if exists "mobile_device_registrations_insert_own" on profiles.mobile_device_registrations;
create policy "mobile_device_registrations_insert_own"
on profiles.mobile_device_registrations
for insert
with check (auth.uid() = user_id);

drop policy if exists "mobile_device_registrations_update_own" on profiles.mobile_device_registrations;
create policy "mobile_device_registrations_update_own"
on profiles.mobile_device_registrations
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "mobile_device_registrations_delete_own" on profiles.mobile_device_registrations;
create policy "mobile_device_registrations_delete_own"
on profiles.mobile_device_registrations
for delete
using (auth.uid() = user_id);

create or replace function profiles.touch_mobile_device_registration_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_mobile_device_registrations_updated_at on profiles.mobile_device_registrations;
create trigger trg_mobile_device_registrations_updated_at
before update on profiles.mobile_device_registrations
for each row
execute function profiles.touch_mobile_device_registration_updated_at();

grant usage on schema profiles to service_role;
grant select, insert, update, delete on profiles.mobile_device_registrations to service_role;
grant select on public.mobile_device_registrations to service_role;
revoke all on public.mobile_device_registrations from anon, authenticated;
