-- ==========================================================
-- REDISENO DE MENSUALIDADES Y REGLAS AUTOMATICAS DE PAGOS
-- Fecha: 2026-05-19
-- ==========================================================

BEGIN;

-- 1) Nuevo catalogo de tipos de mensualidad
CREATE TABLE IF NOT EXISTS billing.membership_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  nombre text NOT NULL,
  detalle text,
  costo numeric(10,2) NOT NULL CHECK (costo > 0),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE billing.membership_types IS 'Catalogo de tipos de mensualidad para pagos del club';
COMMENT ON COLUMN billing.membership_types.code IS 'Codigo tecnico unico del tipo de mensualidad';
COMMENT ON COLUMN billing.membership_types.nombre IS 'Nombre visible del tipo de mensualidad';
COMMENT ON COLUMN billing.membership_types.detalle IS 'Descripcion corta del plan';
COMMENT ON COLUMN billing.membership_types.costo IS 'Costo oficial de la mensualidad';

INSERT INTO billing.membership_types (code, nombre, detalle, costo, active)
VALUES
  ('normal', 'Mensualidad normal', 'Mensualidad normal', 35.00, true),
  ('grupo', 'Mensualidad en grupo', 'Mensualidad en grupo', 32.50, true)
ON CONFLICT (code) DO UPDATE
SET
  nombre = EXCLUDED.nombre,
  detalle = EXCLUDED.detalle,
  costo = EXCLUDED.costo,
  active = EXCLUDED.active,
  updated_at = now();

CREATE OR REPLACE VIEW public.membership_types AS
SELECT
  id,
  code,
  nombre,
  detalle,
  costo,
  active,
  created_at,
  updated_at
FROM billing.membership_types;

CREATE OR REPLACE VIEW public.payments AS
SELECT
  id,
  student_id,
  payment_type_id,
  monto,
  fecha_pago,
  fecha_inicio,
  fecha_fin,
  estado,
  deleted_at,
  membership_type_id
FROM billing.payments;

CREATE OR REPLACE VIEW public.payments_active AS
SELECT
  id,
  student_id,
  payment_type_id,
  monto,
  fecha_pago,
  fecha_inicio,
  fecha_fin,
  estado,
  deleted_at,
  membership_type_id
FROM billing.payments
WHERE deleted_at IS NULL;

-- 2) Seguridad basica de la nueva tabla
ALTER TABLE billing.membership_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Membership types can be read" ON billing.membership_types;
CREATE POLICY "Membership types can be read"
  ON billing.membership_types
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Admins manage membership types" ON billing.membership_types;
CREATE POLICY "Admins manage membership types"
  ON billing.membership_types
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- 3) Alteraciones de billing.payments
ALTER TABLE billing.payments
  ADD COLUMN IF NOT EXISTS membership_type_id bigint;

ALTER TABLE billing.payments
  ALTER COLUMN fecha_pago SET DEFAULT CURRENT_DATE;

UPDATE billing.payments
SET fecha_pago = COALESCE(fecha_pago, fecha_inicio, CURRENT_DATE)
WHERE fecha_pago IS NULL;

ALTER TABLE billing.payments
  ALTER COLUMN fecha_pago SET NOT NULL;

-- 4) Backfill historico de membership_type_id
WITH membership_ids AS (
  SELECT
    MAX(CASE WHEN code = 'normal' THEN id END) AS normal_id,
    MAX(CASE WHEN code = 'grupo' THEN id END) AS grupo_id
  FROM billing.membership_types
)
UPDATE billing.payments p
SET membership_type_id = CASE
  WHEN p.monto = 32.50::numeric(10,2) THEN m.grupo_id
  WHEN p.monto = 35.00::numeric(10,2) THEN m.normal_id
  ELSE m.normal_id
END
FROM membership_ids m
WHERE p.membership_type_id IS NULL;

ALTER TABLE billing.payments
  ALTER COLUMN membership_type_id SET NOT NULL;

ALTER TABLE billing.payments
  DROP CONSTRAINT IF EXISTS payments_membership_type_id_fkey;

ALTER TABLE billing.payments
  ADD CONSTRAINT payments_membership_type_id_fkey
  FOREIGN KEY (membership_type_id)
  REFERENCES billing.membership_types(id);

ALTER TABLE billing.payments
  DROP CONSTRAINT IF EXISTS payments_period_valid_check;

ALTER TABLE billing.payments
  ADD CONSTRAINT payments_period_valid_check
  CHECK (fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_fin >= fecha_inicio);

CREATE INDEX IF NOT EXISTS idx_payments_student_fecha_fin_active
  ON billing.payments (student_id, fecha_fin DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_payments_membership_type_id
  ON billing.payments (membership_type_id);

-- 5) Funciones para calculo de periodo y estado
CREATE OR REPLACE FUNCTION public.calculate_membership_payment_period(
  p_student_id uuid,
  p_fecha_pago date,
  p_exclude_payment_id uuid DEFAULT NULL
) RETURNS TABLE(fecha_inicio date, fecha_fin date)
LANGUAGE plpgsql
AS $$
DECLARE
  v_last_end date;
  v_start date;
BEGIN
  SELECT MAX(p.fecha_fin)
  INTO v_last_end
  FROM billing.payments p
  WHERE p.student_id = p_student_id
    AND p.deleted_at IS NULL
    AND p.id IS DISTINCT FROM p_exclude_payment_id;

  v_start := COALESCE(v_last_end + 1, COALESCE(p_fecha_pago, CURRENT_DATE));

  RETURN QUERY
  SELECT
    v_start,
    (v_start + INTERVAL '1 month' - INTERVAL '1 day')::date;
END;
$$;

CREATE OR REPLACE FUNCTION public.calculate_payment_state(
  p_fecha_fin date
) RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_diff integer;
BEGIN
  IF p_fecha_fin IS NULL THEN
    RETURN 'activo';
  END IF;

  v_diff := p_fecha_fin - CURRENT_DATE;

  IF v_diff < 0 THEN
    RETURN 'vencido';
  END IF;

  IF v_diff <= 5 THEN
    RETURN 'proximo_a_vencer';
  END IF;

  RETURN 'activo';
END;
$$;

-- 6) Trigger de automatizacion
CREATE OR REPLACE FUNCTION public.apply_payment_membership_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, billing, pg_temp
AS $$
DECLARE
  v_cost numeric(10,2);
  v_should_recompute_period boolean;
  v_start date;
  v_end date;
BEGIN
  IF NEW.student_id IS NULL THEN
    RAISE EXCEPTION 'student_id es obligatorio para registrar pagos';
  END IF;

  IF NEW.membership_type_id IS NULL THEN
    RAISE EXCEPTION 'membership_type_id es obligatorio para registrar pagos';
  END IF;

  NEW.fecha_pago := COALESCE(NEW.fecha_pago, CURRENT_DATE);

  SELECT mt.costo
  INTO v_cost
  FROM billing.membership_types mt
  WHERE mt.id = NEW.membership_type_id
    AND mt.active = true;

  IF v_cost IS NULL THEN
    RAISE EXCEPTION 'El tipo de mensualidad % no existe o esta inactivo', NEW.membership_type_id;
  END IF;

  NEW.monto := v_cost;

  IF TG_OP = 'INSERT' THEN
    v_should_recompute_period := true;
  ELSE
    v_should_recompute_period :=
      NEW.student_id IS DISTINCT FROM OLD.student_id
      OR NEW.membership_type_id IS DISTINCT FROM OLD.membership_type_id
      OR NEW.fecha_inicio IS NULL
      OR NEW.fecha_fin IS NULL;
  END IF;

  IF v_should_recompute_period THEN
    SELECT p.fecha_inicio, p.fecha_fin
    INTO v_start, v_end
    FROM public.calculate_membership_payment_period(
      NEW.student_id,
      NEW.fecha_pago,
      CASE WHEN TG_OP = 'UPDATE' THEN NEW.id ELSE NULL END
    ) p;

    NEW.fecha_inicio := v_start;
    NEW.fecha_fin := v_end;
  END IF;

  IF NEW.fecha_fin IS NOT NULL AND NEW.fecha_inicio IS NOT NULL AND NEW.fecha_fin < NEW.fecha_inicio THEN
    RAISE EXCEPTION 'fecha_fin no puede ser menor a fecha_inicio';
  END IF;

  NEW.estado := public.calculate_payment_state(NEW.fecha_fin);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payments_membership_rules_trigger ON billing.payments;
CREATE TRIGGER payments_membership_rules_trigger
BEFORE INSERT OR UPDATE ON billing.payments
FOR EACH ROW
EXECUTE FUNCTION public.apply_payment_membership_rules();

-- Permisos minimos para lectura desde API sin romper trigger/rules
GRANT USAGE ON SCHEMA billing TO authenticated;
GRANT SELECT ON billing.membership_types TO authenticated;

-- 7) Normalizar registros legacy incompletos
UPDATE billing.payments p
SET membership_type_id = p.membership_type_id
WHERE p.deleted_at IS NULL
  AND (p.fecha_inicio IS NULL OR p.fecha_fin IS NULL OR p.estado IS NULL);

-- 8) Sincronizar estado historico al momento de migrar
UPDATE billing.payments p
SET estado = public.calculate_payment_state(p.fecha_fin)
WHERE p.deleted_at IS NULL;

COMMIT;
