flowchart TD
    A[Inicio] --> B[Administrador o entrenador recopila información]

    B --> D[Pagos]

    D --> E[Registro en hojas de cálculo o apuntes]

    E --> K{¿La información está completa?}

    K -->|Sí| L[Se usa para control interno]
    K -->|No| M[Se solicita nuevamente la información]
    M --> B

    L --> N[Fin]